#ifndef PORT_RADIO_H
#define PORT_RADIO_H

#include <stdint.h>

#define RADIO_CMD_CALIBRATIMAGE 0x98U
#define RADIO_CMD_CALIBRATE 0x89U
#define RADIO_CMD_SET_REGULATORMODE 0x96U
#define RADIO_CMD_GET_ERROR 0x17U
#define RADIO_CMD_CLR_ERROR 0x07U
#define RADIO_CMD_CFG_DIOIRQ 0x08U
#define RADIO_CMD_CLR_IRQSTATUS 0x02U
#define RADIO_CMD_GET_IRQSTATUS 0x12U
#define RADIO_CMD_GET_PACKETSTATUS 0x14U
#define RADIO_CMD_GET_PACKETTYPE 0x11U
#define RADIO_CMD_GET_RSSIINST 0x15U
#define RADIO_CMD_GET_RXBUFFERSTATUS 0x13U
#define RADIO_CMD_GET_STATS 0x10U
#define RADIO_CMD_GET_STATUS 0xC0U
#define RADIO_CMD_RESET_STATS 0x00U
#define RADIO_CMD_SET_BUFFERBASEADDRESS 0x8FU
#define RADIO_CMD_SET_CAD 0xC5U
#define RADIO_CMD_SET_CADPARAMS 0x88U
#define RADIO_CMD_SET_FS 0xC1U
#define RADIO_CMD_SET_LORASYMBTIMEOUT 0xA0U
#define RADIO_CMD_SET_MODULATIONPARAMS 0x8BU
#define RADIO_CMD_SET_PACKETPARAMS 0x8CU
#define RADIO_CMD_SET_PACONFIG 0x95U
#define RADIO_CMD_SET_PACKETTYPE 0x8AU
#define RADIO_CMD_SET_RFFREQUENCY 0x86U
#define RADIO_CMD_SET_RX 0x82U
#define RADIO_CMD_SET_RXDUTYCYCLE 0x94U
#define RADIO_CMD_SET_TXRXFALLBACKMODE 0x93U
#define RADIO_CMD_SET_SLEEP 0x84U
#define RADIO_CMD_SET_STANDBY 0x80U
#define RADIO_CMD_SET_STOPRXTIMERONPREAMBLE 0x9FU
#define RADIO_CMD_SET_TCXOMODE 0x97U
#define RADIO_CMD_SET_TX 0x83U
#define RADIO_CMD_SET_TXCONTINUOUSWAVE 0xD1U
#define RADIO_CMD_SET_TXCONTINUOUSPREAMBLE 0xD2U
#define RADIO_CMD_SET_TXPARAMS 0x8EU
#define RADIO_CMD_WRITE_BUFFER 0x0EU
#define RADIO_CMD_WRITE_REGISTER 0x0DU
#define RADIO_CMD_READ_BUFFER 0x1EU
#define RADIO_CMD_READ_REGISTER 0x1DU

#endif /* PORT_RADIO_H */
