#ifndef PORT_CLOCK_H
#define PORT_CLOCK_H

void dma1_clock_enable(void);
void dma2_clock_enable(void);
void dmamux1_clock_enable(void);
void cordic_clock_enable(void);
void fmac_clock_enable(void);
void flash_clock_enable(void);
void crc_clock_enable(void);
void gpioa_clock_enable(void);
void gpiob_clock_enable(void);
void gpiof_clock_enable(void);
void gpiog_clock_enable(void);
void adc12_clock_enable(void);
void dac1_clock_enable(void);
void dac3_clock_enable(void);
void aes_clock_enable(void);
void rng_clock_enable(void);
void tim1_clock_enable(void);
void tim2_clock_enable(void);
void tim3_clock_enable(void);
void tim4_clock_enable(void);
void tim6_clock_enable(void);
void tim7_clock_enable(void);
void rtc_clock_enable(void);
void wwdg_clock_enable(void);
void spi2_clock_enable(void);
void spi3_clock_enable(void);
void usart2_clock_enable(void);
void i2c1_clock_enable(void);
void i2c2_clock_enable(void);
void usb_clock_enable(void);
void fdcan_clock_enable(void);
void pwr_clock_enable(void);
void i2c3_clock_enable(void);
void lptim1_clock_enable(void);
void lpuart1_clock_enable(void);
void ucpd1_clock_enable(void);
void syscfg_clock_enable(void);
void tim1_clock_enable(void);
void spi1_clock_enable(void);
void tim8_clock_enable(void);
void usart1_clock_enable(void);
void tim15_clock_enable(void);
void tim16_clock_enable(void);
void tim17_clock_enable(void);
void sai1_clock_enable(void);

#endif /* PORT_CLOCK_H */
